### ISSUE TITLE
Out of the box syntax error

### ISSUE THREAD

**Issue by cbg342** [lugia19/elevenlabslib#1]
When trying to "from elevenlabslib import *"
It gives:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cameronglass/opt/anaconda3/lib/python3.9/site-packages/elevenlabslib/__init__.py", line 1, in <module>
    from .ElevenLabsUser import ElevenLabsUser
  File "/Users/cameronglass/opt/anaconda3/lib/python3.9/site-packages/elevenlabslib/ElevenLabsUser.py", line 10, in <module>
    from elevenlabslib.helpers import *
  File "/Users/cameronglass/opt/anaconda3/lib/python3.9/site-packages/elevenlabslib/helpers.py", line 11
    match requestType:
          ^
SyntaxError: invalid syntax

**Comment by lugia19** [comment]
Right, I forgot that match case is 3.10+ only. Fixed.

**Comment by cbg342** [comment]
> Right, I forgot that match case is 3.10+ only. Fixed.

Thank you! Amazing wrapper btw, thanks for the work 🙏
